version: '3'

services:
  server:
    build: .
    container_name: test_backend
    restart: always
    command: npm start
    ports:
      - 8080:8080
    volumes:
      - ./:/data
      - ./logs:/usr/src/app/logs

